params:
    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "https://github.com/tk-zzz.png" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"

    socialIcons: # optional
        - name: Github
          url: "https://github.com/"
        - name: "<platform 2>"
          url: "<link2>"
