params:
    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "https://github.com/tk-zzz.png" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: github
              url: "https://github.com/tk-zzz/"

    socialIcons: # optional
        - name: github
          url: "https://github.com/tk-zzz/"
